name: "CD_PR"

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'

jobs:
  test:
    name: Set Up, Build and Test
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
      DOTNET_MULTILEVEL_LOOKUP: 0
      DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: true
      TERM: xterm

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.113

    - name: Install PNPM
      run: npm install --global pnpm

    - name: Install Nx Dependencies
      run: pnpm install

    - name: Build API
      run: npx nx build api

    - name: Build API - TEST
      run: npx nx build api-test

    - name: Test
      run: npx nx test api-test

  check_commits_convetion:
    name: Conventional Commits Message
    runs-on: ubuntu-latest
    steps:
      - uses: gsactions/commit-message-checker@v2
        with:
          pattern: '(?:feat|fix|chore|test|docs|build|ci|style|refactor|perf|revert)(?:\(\w+\))?:\s[a-z]{1,2}.+'
          error: 'The commit message must have the following structure: <type>(?): <description>'
          excludeDescription: 'true'
          excludeTitle: 'true'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}

  check_branches_convention:
    name: Conventional Branches Name
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: '([a-z]+)/([a-z]+)'
          allowed_prefixes: 'jlteran,resprella,bsoliz,lespinoza,horopeza,jtancara,stable,fix,chore,docs,feat,build,ci,refactor,perf,hotfix'
          ignore: main,release,develop,feature,test
          min_length: 4
          max_length: 100
